### ISSUE TITLE
ArgumentNullException saving settings

### ISSUE THREAD

**Issue by ribbles** [csnate/cctray-jenkins-transport#19]
Configure https jenkins server. Successfully able to connect and select projects. After hitting OK on the settings screen the following error pops up.

`Unhandled exception: System.ArgumentNullException: Value cannot be null.
Parameter name: key
   at System.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Collections.Generic.Dictionary``2.FindEntry(TKey key)
   at System.Collections.Generic.Dictionary``2.ContainsKey(TKey key)
   at JenkinsTransport.EnumUtils.GetIntegrationStatus(String color)
   at JenkinsTransport.Api.GetProjectStatus(XDocument xDoc, ProjectStatus currentStatus)
   at JenkinsTransport.JenkinsServerManager.<GetCruiseServerSnapshotEx>b__1(JenkinsJob a)
   at System.Linq.Enumerable.WhereSelectListIterator``2.MoveNext()
   at System.Collections.Generic.List``1..ctor(IEnumerable``1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable``1 source)
   at JenkinsTransport.JenkinsServerManager.GetCruiseServerSnapshotEx()
   at JenkinsTransport.JenkinsTransportExtension.GetProjectWebUrl(String projectName, JenkinsProjectManager manager)
   at JenkinsTransport.JenkinsTransportExtension.RetrieveProjectManager(String projectName)
   at ThoughtWorks.CruiseControl.CCTrayLib.Monitoring.CruiseProjectManagerFactory.Create(CCTrayProject project, IDictionary``2 serverManagers)
   at ThoughtWorks.CruiseControl.CCTrayLib.Configuration.CCTrayMultiConfiguration.GetProjectStatusMonitors(ISingleServerMonitor[] serverMonitors)
   at ThoughtWorks.CruiseControl.CCTrayLib.Presentation.MainFormController..ctor(ICCTrayMultiConfiguration configuration, ISynchronizeInvoke owner, MainForm mainForm)
   at ThoughtWorks.CruiseControl.CCTrayLib.Presentation.MainForm.CreateController()
   at ThoughtWorks.CruiseControl.CCTrayLib.Presentation.MainForm.ReloadConfiguration(Func``1 loadPreferences)
   at System.Windows.Forms.MenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.Command.Invoke()
   at System.Windows.Forms.NotifyIcon.WndProc(Message& msg)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)`

ccTray 1.8.4.0
cctray-jenkins-transport 1.1.0
Jenkins 2.150.3

**Comment by ribbles** [comment]
Fixed in #20
